# Generated by Django 5.2.1 on 2025-06-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReadWise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(max_length=255)),
                ("data_lancamento", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
