# Generated by Django 5.2.3 on 2025-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readWise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Romance", "Romance"),
                            ("Fantasia", "Fantasia"),
                            ("Acadêmico", "Acadêmico"),
                            ("Policial", "Policial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capa_url", models.URLField()),
            ],
        ),
    ]
