# Generated by Django 5.2.3 on 2025-06-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readWise", "0002_ebook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ebook",
            name="capa_url",
        ),
        migrations.AddField(
            model_name="ebook",
            name="capa",
            field=models.ImageField(blank=True, null=True, upload_to="capas/"),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="autor",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="categoria",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
