# Generated by Django 5.2.3 on 2025-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "readWise",
            "0003_remove_ebook_capa_url_ebook_capa_alter_ebook_autor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ebook",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
