# Generated by Django 5.2.3 on 2025-06-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readWise", "0006_livroadquirido"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanosAssinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("quantidade_livros", models.PositiveIntegerField()),
                ("generos", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
