# Generated by Django 5.2.3 on 2025-06-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readWise", "0007_planosassinatura"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_site", models.CharField(max_length=100)),
                ("email_suporte", models.EmailField(max_length=254)),
                ("moeda_padrao", models.CharField(max_length=10)),
                ("livros_gratis_geral", models.PositiveIntegerField(default=0)),
                ("livros_gratis_romance", models.PositiveIntegerField(default=0)),
                ("livros_gratis_policial", models.PositiveIntegerField(default=0)),
                ("livros_gratis_fantasia", models.PositiveIntegerField(default=0)),
                ("livros_gratis_academico", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Configuração do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
            },
        ),
    ]
