# Generated by Django 5.2.3 on 2025-06-19 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readWise", "0010_itemcarrinho"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="data_pedido",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="pedido",
            old_name="user",
            new_name="usuario",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="ebook",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="preco",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="status_pagamento",
        ),
        migrations.AddField(
            model_name="pedido",
            name="pago",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "ebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="readWise.ebook"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="readWise.pedido",
                    ),
                ),
            ],
        ),
    ]
