# Generated by Django 5.2.3 on 2025-06-20 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readWise", "0011_rename_data_pedido_pedido_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco_desconto", models.DecimalField(decimal_places=2, max_digits=6)),
                ("inicio", models.DateField()),
                ("fim", models.DateField()),
                (
                    "ebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="readWise.ebook"
                    ),
                ),
            ],
        ),
    ]
